require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Gemfile
    - jekyll-mentioji.gemspec
    - lib/**/*.rb
    - features/**/*.rb
  Exclude:
    - benchmark/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
