language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.6.2
  - 2.4.6

env:
  - JEKYLL_VERSION="~> 3.8" PLUGINS=jekyll-mentioji
  - JEKYLL_VERSION="~> 3.8" PLUGINS=jekyll-mentions:jemoji
  - JEKYLL_VERSION=">= 4.0.0.pre.alpha1" PLUGINS=jekyll-mentioji
  - JEKYLL_VERSION=">= 4.0.0.pre.alpha1" PLUGINS=jekyll-mentions:jemoji

script:
 - bundle exec cucumber
 - bundle exec rubocop
