language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.6.2
  - 2.3.8

env:
  - PLUGINS=jekyll-mentioji
  - PLUGINS=jekyll-mentions:jemoji

script:
 - bundle exec cucumber
 - bundle exec rubocop
